name: apphud
description: Apphud SDK is a lightweight open-source library to manage auto-renewable subscriptions and other in-app purchases in your Flutter app.
version: 1.0.1
homepage: 'https://apphud.com'
repository: 'https://github.com/apphud/ApphudSDK-Flutter'

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        package: com.apphud.app
        pluginClass: AppHudPlugin
      ios:
        pluginClass: AppHudPlugin
